spring:
  datasource:
    url: jdbc:mysql://localhost:3306/restapi
    username: root
    password:
    driverClassName: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

aws:
  bucket: ishihara-image
  dir: images/products/
  accessKey: ${AWS_ACCESS_KEY_ID}
  secretKey: ${AWS_SECRET_ACCESS_KEY}
  region: ap-northeast-1

